### ISSUE TITLE
Unable to deploy - TypeError: Cannot read property 'fromRed' of null

### ISSUE THREAD

**Issue by vladpanov** [connext/chaindata#1]
Hi,

After entering all of the information for Binance deployment, I am getting the following error when running _node deploy.js_:
**TypeError: Cannot read property 'fromRed' of null**

```
/Users/vlad/Documents/_DEV/chaindata/node_modules/elliptic/lib/elliptic/curve/short.js:415
  return this.x.fromRed();
                ^

TypeError: Cannot read property 'fromRed' of null
    at Point.getX (/Users/vlad/Documents/_DEV/chaindata/node_modules/elliptic/lib/elliptic/curve/short.js:415:17)
    at Point._encode (/Users/vlad/Documents/_DEV/chaindata/node_modules/elliptic/lib/elliptic/curve/base.js:300:16)
    at Point.encode (/Users/vlad/Documents/_DEV/chaindata/node_modules/elliptic/lib/elliptic/curve/base.js:309:28)
    at KeyPair.getPublic (/Users/vlad/Documents/_DEV/chaindata/node_modules/elliptic/lib/elliptic/ec/key.js:66:19)
    at new SigningKey (/Users/vlad/Documents/_DEV/chaindata/node_modules/@ethersproject/signing-key/lib/index.js:22:71)
    at new Wallet (/Users/vlad/Documents/_DEV/chaindata/node_modules/@ethersproject/wallet/lib/index.js:123:36)
    at Object.<anonymous> (/Users/vlad/Documents/_DEV/chaindata/deploy.js:59:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

In terms of changes, I've only updated the required 39 - 55:
```
const provider = new ethers.providers.JsonRpcProvider('https://bsc-dataseed1.binance.org/');
const verifyURL = 'https://api.bscscan.com/api';
const privateKey = Buffer.from('0x1e...', 'hex');
const apikey = 'VKVS...';

const mpcAddress = '0x533e3c0e6b48010873B947bddC4721b1bDFF9648';
const signer = new ethers.Wallet(privateKey, provider);
const constructorArgs = ['<name>', '<symbol>', '18', '', signer.address];
```

Any guidance would be super appreciated. Thank you!

**Comment by psykeeper** [comment]
Hi @vladpanov , could you please try pulling https://github.com/connext/chaindata/pull/3 and verifying that it fixes this issue?
